### ISSUE TITLE
Server Restarts when Client File Changes

### ISSUE THREAD

**Issue by davidrichied** [JZ-FE/vue-ssr-template#1]
Hi,
I noticed that the nodejs server restarts each time a file ending in .js changes. For example, if I change the /src/views/item/index.js file, the nodejs server restarts. For me, server restarts take a long time, but client file recompiles are very quick. Is there any way to prevent the server from restarting when a change is made to a client file?
A few files that I don't believe need a full server restart are all the files in the following directories: view, store, router, and plugins.
Your input is appreciated. Thanks.

**Comment by billwing** [comment]
Sorry, I can't solve it. You can go to https://github.com/vuejs/vue-hackernews-2.0 and submit new issue.
